config/routes.rb
Rails.application.routes.draw do

  get '/now_following' => 'epicenter#now_following'
  get '/unfollow' => 'epicenter#unfollow'
  get '/tag_tweets' => 'epicenter#tag_tweets'
  get '/all_users' => 'epicenter#all_users'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'
  
  resources :tweets
  devise_for :users

  get '/:username' => 'epicenter#show_user', as: :show_user
  
  root 'epicenter#feed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :tweet_tags
  has_many :tags, through: :tweet_tags
  
  validates :message, presence: true
  validates :message, length: { maximum: 140, too_long: "Everyone knows a tweet is only 140 characters!"}, on: :create

  before_validation :link_check, on: :create
  after_validation :apply_link, on: :create

  private

  def apply_link
    arr = self.message.split
    index = arr.map { |x| x.include?("http://") || x.include?("https://") }.index(true)

    if index
      url = arr[index]
      arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
    end

    self.message = arr.join(" ")
  end
  
  def link_check
    check = false
    if self.message.include?("http://") || self.message.include?("https://")
      check = true
    else
      check = false
    end
    
    if check == true
      arr = self.message.split
      index = arr.map{ |x| x.include? "http"}.index(true)
      self.link = arr[index]
      if arr[index].length > 23
        arr[index] = "#{arr[index][0..20]}..."
      end
      
      self.message = arr.join(" ")
    end
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable# , :omniauthable

  has_many :tweets

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, uniqueness: true
  validates :tag_color, format: { with: /\A#[0-9A-Fa-f]{6}\z/ }

  serialize :following, Array

  def followers
    User.all.select{ |u| u.following.include? self.id }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_params, if: :devise_controller?

  protected
  
  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [:username, :name, :bio, :location, :avatar, :following, :tag, :tag_color])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

  before_action :authenticate_user!
  
  def feed
    @following_tweets = Tweet.where(user_id: current_user.following + [current_user.id]).order(created_at: :desc)   
  end

  def show_user
    @user = User.find_by(username: params[:username])
    redirect_to root_path if @user.nil?
  end

  def now_following
    user = User.find(params[:id].to_i)
    current_user.following.push(user.id)
    current_user.save

    redirect_to show_user_path(user.username)
  end

  def unfollow
    user = User.find(params[:id].to_i)
    current_user.following.delete(user.id)
    current_user.save

    redirect_to show_user_path(user.username)
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def all_users
    @users = User.all
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    @users = []
    
    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include TweetsHelper
  
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)
    @tweet = get_tagged(@tweet)
    
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_tagged(tweet)
    message_arr = tweet.message.split

    message_arr.each_with_index do|word, index|
      if word[0] == '#'
        # Create a new tag
        if Tag.pluck(:phrase).include?(word)
          # Tag exists
          tag =Tag.find_by(phrase: word)
        else
          # Tag does not exist, create new tag
          tag =Tag.create(phrase: word)
        end
        # Create the TweetTag
        tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        # #techlife => <a href='tag_tweets?id=1'>#techlife</a>
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end
    tweet.message = message_arr.join(' ')
    return tweet
  end
end

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
  <div class="col-md-3">
    <div class="well user-list-wells">
      <div class="row">
	<div class="col-md-6">
	  <%= image_tag user.avatar.url, class: "avatar", height: '20', width: '20' %>
	</div>
	<div class="col-md-6">
	  <p>
	    <% if current_user.following.include?(user.id) %>
	    <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary unfollow_btn" %>
	    <% else %>
	    <% if current_user.id != user.id %>
	    <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
	    <% end %>
	    <% end %>
	  </p>
	</div>
      </div>
      <div class="row">
	<%= link_to show_user_path(username: user.username) do %>
	<h3><%= user.name %></h3>
	<p><%= user.username %></p>
	<% end %>
	<p>
	  <%= user.bio %>
	</p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/epicenter/all_users.html.erb
<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="feed-well well" id="profile-card">
      <%= render 'users/avatar', { user: current_user } %>
      <div><strong><%= current_user.name %></strong></div>
      <div>@<%= current_user.username %></div>
      <div>
	<ul>
	  <li><%= current_user.tweets.count %> Tweets</li>
	  <%= link_to following_path(id: current_user.id) do %>
	  <li>Following <%= pluralize current_user.following.count, 'user' %>.</li>
	  <% end %>
	  <%= link_to followers_path(id: current_user.id) do %>
	  <li>Followed by <%= pluralize current_user.followers.count, 'user' %>.</li>
	  <% end %>
	  
	</ul>
      </div>
    </div>

    <div class="feed-well well" id="trends-card">
      <h2>Trends</h2>
    </div>
  </div>
  
  <div class="col-md-6">
    <% if @following_tweets.any? %>
      <% @following_tweets.each do |tweet| %>
        <%= render 'tweets/tweet_panel', { tweet: tweet } %>
      <% end %>
    <% else %>
      <div class="panel">
	<p>No tweets to show. Consider following another user or writing your own tweet!</p>
      </div>
    <% end %>
  </div>


  <div class="col-md-3">
    <div class="feed-well well">
      <h2>Who to follow</h2>
      <ul>
	<li>A celebrity</li>
	<li>A politician</li>
	<li>Your cat</li>
      </ul>
    </div>
  </div>
</div>
  

app/views/epicenter/followers.html.erb
<h2><%= @user.username %>'s Followers</h2>
<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h2><%= @user.username %> is following</h2>
<%= render 'user_list' %>

app/views/epicenter/show_user.html.erb
<div class="row">
  <div class="col-md-12" style="text-align: center;">
    <h1><%= @user.username %>'s Profile & Tweets</h1>
    <p>
      <% if current_user.following.include?(@user.id) %>
        <%= link_to "Following", unfollow_path(id: @user.id),
	    class: "btn btn-primary", id: "unfollow_btn" %>
	  
      <% else %>
        <% if current_user.id != @user.id %>
          <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="well">
      <p><h2><%= @user.name %></h2></p>
      <p><strong>Location:</strong> <%= @user.location %></p>
      <p><h3>Bio</h3></p>
      <p><%= @user.bio %></p>
    </div>
  </div>

  <div class="col-md-6">
    <% if @user.tweets.any? %>
      <% @user.tweets.each do |tweet| %>
        <%= render 'tweets/tweet_panel', { tweet: tweet } %>
      <% end %>
    <% else %>
      <div class="panel">
	<%= @user.username %> has no tweets to show. :(
      </div>
    <% end %>
      
  </div>

  <div class="col-md-3">
    <div class="well">
      <h2>Who to follow</h2>
      <ul>
	<li>A celebrity</li>
	<li>A politician</li>
	<li>Your cat</li>
      </ul>
    </div>
  </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<div>
  <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
  <!-- a place for current user stats -->
  <div>
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
    <p>
      <%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
      • <%= time_ago_in_words(tweet.created_at) %>
    </p>
    <p>
      <%= tweet.message.html_safe %>
    </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  </button>
	  <%= link_to "Home", root_path, class: "navbar-brand" %>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav">
	    <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
	    <li><%= link_to "All Users", all_users_path %></li>
	  </ul>
	  <ul class="nav navbar-nav navbar-right">
	    <% if user_signed_in? %>
	    <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		<%= render 'users/avatar', { user: current_user } %>
		<% if current_user.tag %>
		<%= tag.span current_user.tag, style: "color: ##{current_user.tag_color}" %>
		<% end %>
		@<%= current_user.username %> <span class="caret"></span></a>
	      <ul class="dropdown-menu">
		<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
		<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	      </ul>
	    </li>
	    <% end %>
	  </ul>
	</div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :tweet_message, class: 'form-control', id: 'new-tweet-body' %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tweets/_tweet_panel.html.erb
<div class="panel tweet">
  <p>
    <%= link_to show_user_path(tweet.user.username) do %>
    <%= render "users/avatar", {user: tweet.user} %>
    <strong><%= tweet.user.name %></strong> @<%= tweet.user.username %>
    <% end %>
    |
    <%= time_ago_in_words(tweet.created_at) if (Time.now - tweet.created_at) < 1.day %>
    <%= tweet.created_at.strftime('%b %d') if (Time.now - tweet.created_at) >= 1.day %>
  </p>
  <p><%= tweet.message.html_safe %></p>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= link_to tweet.user.username, show_user_path(tweet.user.username) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>New Tweet</h1>

    <%= render 'form', tweet: @tweet %>

    <%= link_to 'Back', tweets_path %>
  </div>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(@tweet.user.username) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/_avatar.html.erb
<%= image_tag user.avatar.url, size:25, class: "user-pic-nav" %>